### PR TITLE
joyent/mdb_v8#54: Improve documentation on how to find the appropriate function address (`addr`) when using `::jsclosure`

### LINKED ISSUE #54: Improve documentation on how to find the appropriate function address (`addr`) when using `::jsclosure`
The [current documentation for `::jsclosure`](https://github.com/joyent/mdb_v8/blob/master/docs/usage.md#jsclosure) mentions:

```
Given a function identified by addr
```

but it's not clear what address `addr` is referring to, especially since by default `::jsstack` doesn't display the `JSFunction` instance's address.

Several users asked me for help on how to find the proper address to use with `::jsclosure`, which makes  me think that this aspect of `::jsclosure`'s documentation should be clearer and more explicit.

### PR DESCRIPTION
**Pull request by misterdjules**
Fixes #54.

/cc @joshwilsdon since he hit this user experience issue recently, and I'd be interested in his feedback.

### CODE REVIEW

**Comment by davepacheco** [comment]
This looks great.  My only suggestion is to move this to a separate section called "Working with JSFunctions" or the like and link it from the jsclosure docs.  This content also applies to jssource, jsconstructor, and potentially others.  In the future, we may extend that new section to cover finding addresses for all kinds of objects and what those addresses mean.

**Comment by misterdjules** [comment]
@davepacheco I ended up adding the new section as a FAQ entry, because it seemed that adding it as a tutorial about functions would have required a significant rewrite that I don't have the time to do right now.

If that's not the way we want to integrate it to the documentation, it's totally fine, I'll just need to spend more time rewriting that content later :)

**Comment by davepacheco** [comment]
This looks good to me.  Feel free to land, or once the commits are squashed I can do it.  Thanks!

**Comment by misterdjules** [comment]
Thank you! Landed in e11c36ae427f1ded32790feb7c77e15d10d96d66.

**Pull request closed without merging**
