### PR TITLE
fix crash on ::findjsobjects -r

### LINKED ISSUE #68: Crash on ::findjsobjects -r with Node v4.3.1 (V8 4.5.103.35)
Hi, not glad to report that the master branch's
`::findjsobjects -r`
crashes on NodeJS Image 15.4.1 (NodeJS version 4.3.1):

```
[root@nodejs-15_4_1 ~]# mdb -p 94743
Loading modules: [ ld.so.1 libumem.so.1 libc.so.1 ]
> ::load /root/mdb_v8.so
mdb_v8 version: 1.1.2 (dev)
V8 version: 4.5.103.35
Autoconfigured V8 support from target
C++ symbol demangling enabled
> 521609209::findjsobjects -r

*** mdb: received signal SEGV at:
    [1] mdb_v8.so`findjsobjects_references_add+0x0()
    [2] mdb_v8.so`jsobj_properties+0xea()
    [3] mdb_v8.so`dcmd_findjsobjects+0x4f0()
    [4] mdb`dcmd_invoke+0x7c()
    [5] mdb`mdb_call_idcmd+0x112()
    [6] mdb`mdb_call+0x3e1()
    [7] mdb`yyparse+0xd7c()
    [8] mdb`mdb_run+0x2cd()
    [9] mdb`main+0xc9d()
    [10] mdb`_start+0x6c()

mdb: (c)ore dump, (q)uit, (r)ecover, or (s)top for debugger [cqrs]? 
```

### PR DESCRIPTION
**Pull request by misterdjules**
Fixes #68. Tested with `tools/runtests_node`: all tests pass.

### CODE REVIEW

**Comment by davepacheco** [comment]
Thanks for doing this, and sorry about the bug.

Can you make the check "val != NULL"?  I think that's part of cstyle, but isn't checked by the tool.  (I think it's a good idea anyway.)

Do you understand why the previous change introduced the problem?  It seems like there were already cases where we passed NULL there, but it doesn't seem like they'd be seen here.

**Comment by misterdjules** [comment]
@davepacheco Updated the PR with the change you suggested. If I merge this change myself, I'll squash all commits in that branch into one commit before merging it.

**Comment by misterdjules** [comment]
Actually, I just saw one test failure, updating the newly added test now to fix that.

**Comment by misterdjules** [comment]
> Actually, I just saw one test failure, updating the newly added test now to fix that.

Done with https://github.com/joyent/mdb_v8/pull/69/commits/06feef5227e92b9509a8688d68a59a01c335d21e.

**Comment by davepacheco** [comment]
LGTM.  Thanks!

**Comment by misterdjules** [comment]
Squashed all commits into one, merging asap.

**Comment by misterdjules** [comment]
Merged with 259e534aa8d3217a0e2f5ef2c8070f148b4d805c. I realize I forgot to update `CHANGES.md`, will do in a subsequent commit. Sorry about that.

**Pull request closed without merging**
