### PR TITLE
joyent/mdb_v8#66: mdb_v8 does not support core files generated by processes that use V8 bundled with node v6.0.0

### LINKED ISSUE #66: mdb_v8 does not support core files generated by processes that use V8 bundled with node v6.0.0
All tests suites but `test/standalone/tst.postmortem_jsstack.js` fail with node v6.0.0.

The V8 version that ships with node v6.0.0 is 5.0.71.35. In comparison, the latest 5.x version of node (v5.11.0) ships with V8 at version 4.6.85.31. It is likely that a lot of changes that break mdb_v8 went into V8 between these two versions, but here are the ones that I was able to find so far:

1.  ["Replace global object link with native context link in all contexts"](https://github.com/v8/v8/commit/47502a238b8185a864bfe6a8d5508b4e67cad40e) and "[\[runtime\] Use "the hole" instead of smi 0 as sentinel for context extension"](https://github.com/v8/v8/commit/9e6448813d41858c3f879ecde41b13bda0770673), which break `test/standalone/tst.jsclosure.js` and more specifically the `::v8context` command.

2. ["Move properties from JSObject to JSReceiver"](https://github.com/v8/v8/commit/4143a667b87f43cb6ff614f328b358ee0d5695fc) which breaks any test that accesses objects' properties, or in other words most tests. 

I would be surprised if these were the only breaking changes, but I wanted to start documenting them as I  go. I'll start working on fixes asap, and will keep this issue updated.

### PR DESCRIPTION
**Pull request by misterdjules**
I've run `make test` and `tools/runtests_node` and verified that all tests pass.

Some comments on the changes themselves:

1. JS objects' properties are now stored in the `JSReceiver` class, which means that we might be able to display properties of instances of classes that are subclasses of `JSReceiver` but that are not subclasses of `JSObject`. As a result, we would probably need to make `::findjsobjects` find such objects. This PR does not take care of that, because I thought this would be better done in a separate change if deemed worthy.

2. Even though the context of a function now stores a reference to the native context instead of the global object for V8 versions > 4.9, this PR still stores the value of the index where the native context is in a variable named `V8_CONTEXT_IDX_GLOBAL`. The reason is that wasn't sure if we wanted to expose this difference to end users, and thus I haven't yet changed [the `v8context_fields` array](https://github.com/joyent/mdb_v8/blob/master/src/mdb_v8_function.c#L81) to store a `"native context"` static field in case V8 version > 4.9 and a `"global object"` otherwise. I think this is what we want to do, but I thought I'd ask for feedback before doing that.

3. The `Context` constants have been added to V8's `tools/gen-postmortem-metadata.py`, [but as offsets instead of constants](https://chromium.googlesource.com/v8/v8.git/+/master/tools/gen-postmortem-metadata.py#191). This seems like this is not what we want, and that these should be defined as constants instead. If we're on the same page about this, I'll follow-up with a PR to V8 to fix it.

Fixes #66.

### CODE REVIEW

**Comment by misterdjules** [comment]
https://github.com/joyent/mdb_v8/pull/67/commits/6522412de1eea29034dae6a5048192c5ba0e3d93 addresses point 2).

**Comment by misterdjules** [comment]
Ping @davepacheco.

**Comment by davepacheco** [comment]
I apologize for the delay -- I thought I had looked at this already.  The change looks good to me.

**Comment by misterdjules** [comment]
Rebased on top of master and squashed into one commit, will merge asap.

**Comment by misterdjules** [comment]
Merged in 6d58b53414b5b88d82b501cb4b815c7b1a55b762.

**Pull request closed without merging**
